#ifndef ARKANOID_DEFINITIONS_H
#define ARKANOID_DEFINITIONS_H

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768
#define APPLICATION_TITLE "Arkanoid"



#define SPLASH_STATE_BACKGROUND_FILEPATH "../assets/splash_state_background.jpg"



#endif //ARKANOID_DEFINITIONS_H
